# Generated by Django 5.1.3 on 2024-11-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyword',
            name='date',
            field=models.DateField(),
        ),
    ]
